### PR TITLE
Updates androidlibrary and androidcommon library to the latest version

### LINKED ISSUE #7: Add ODK 2.1 support
AIDL names should be updated to match the new ODK 2.1 API

### PR DESCRIPTION
**Pull request by DreamyPhobic**
Closes #7 and also adds missing dependency ```com.android.support:preference``` in build.gradle file.

### CODE REVIEW

**Review by jbeorse — COMMENTED** [review]
Have you tested this to build and run successfully?

**Comment by DreamyPhobic** [comment]
Yes, I have checked it with Android 8.1

**Comment by linl33** [comment]
Does this also fix the 2nd crash in linked comment? 
https://github.com/opendatakit/skunkworks-bat/issues/9#issuecomment-472879479

**Comment by DreamyPhobic** [comment]
yes

**Comment by DreamyPhobic** [comment]
But give another crash as reported in #19 for me.

**Comment by DreamyPhobic** [comment]
@jbeorse @linl33 please review?

**Pull request merged**
